require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe QualificacoesController do

  # This should return the minimal set of attributes required to create a valid
  # Qualificacao. As you add validations to Qualificacao, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "cliente_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # QualificacoesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all qualificacoes as @qualificacoes" do
      qualificacao = Qualificacao.create! valid_attributes
      get :index, {}, valid_session
      assigns(:qualificacoes).should eq([qualificacao])
    end
  end

  describe "GET show" do
    it "assigns the requested qualificacao as @qualificacao" do
      qualificacao = Qualificacao.create! valid_attributes
      get :show, {:id => qualificacao.to_param}, valid_session
      assigns(:qualificacao).should eq(qualificacao)
    end
  end

  describe "GET new" do
    it "assigns a new qualificacao as @qualificacao" do
      get :new, {}, valid_session
      assigns(:qualificacao).should be_a_new(Qualificacao)
    end
  end

  describe "GET edit" do
    it "assigns the requested qualificacao as @qualificacao" do
      qualificacao = Qualificacao.create! valid_attributes
      get :edit, {:id => qualificacao.to_param}, valid_session
      assigns(:qualificacao).should eq(qualificacao)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Qualificacao" do
        expect {
          post :create, {:qualificacao => valid_attributes}, valid_session
        }.to change(Qualificacao, :count).by(1)
      end

      it "assigns a newly created qualificacao as @qualificacao" do
        post :create, {:qualificacao => valid_attributes}, valid_session
        assigns(:qualificacao).should be_a(Qualificacao)
        assigns(:qualificacao).should be_persisted
      end

      it "redirects to the created qualificacao" do
        post :create, {:qualificacao => valid_attributes}, valid_session
        response.should redirect_to(Qualificacao.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved qualificacao as @qualificacao" do
        # Trigger the behavior that occurs when invalid params are submitted
        Qualificacao.any_instance.stub(:save).and_return(false)
        post :create, {:qualificacao => { "cliente_id" => "invalid value" }}, valid_session
        assigns(:qualificacao).should be_a_new(Qualificacao)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Qualificacao.any_instance.stub(:save).and_return(false)
        post :create, {:qualificacao => { "cliente_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested qualificacao" do
        qualificacao = Qualificacao.create! valid_attributes
        # Assuming there are no other qualificacoes in the database, this
        # specifies that the Qualificacao created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Qualificacao.any_instance.should_receive(:update_attributes).with({ "cliente_id" => "1" })
        put :update, {:id => qualificacao.to_param, :qualificacao => { "cliente_id" => "1" }}, valid_session
      end

      it "assigns the requested qualificacao as @qualificacao" do
        qualificacao = Qualificacao.create! valid_attributes
        put :update, {:id => qualificacao.to_param, :qualificacao => valid_attributes}, valid_session
        assigns(:qualificacao).should eq(qualificacao)
      end

      it "redirects to the qualificacao" do
        qualificacao = Qualificacao.create! valid_attributes
        put :update, {:id => qualificacao.to_param, :qualificacao => valid_attributes}, valid_session
        response.should redirect_to(qualificacao)
      end
    end

    describe "with invalid params" do
      it "assigns the qualificacao as @qualificacao" do
        qualificacao = Qualificacao.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Qualificacao.any_instance.stub(:save).and_return(false)
        put :update, {:id => qualificacao.to_param, :qualificacao => { "cliente_id" => "invalid value" }}, valid_session
        assigns(:qualificacao).should eq(qualificacao)
      end

      it "re-renders the 'edit' template" do
        qualificacao = Qualificacao.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Qualificacao.any_instance.stub(:save).and_return(false)
        put :update, {:id => qualificacao.to_param, :qualificacao => { "cliente_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested qualificacao" do
      qualificacao = Qualificacao.create! valid_attributes
      expect {
        delete :destroy, {:id => qualificacao.to_param}, valid_session
      }.to change(Qualificacao, :count).by(-1)
    end

    it "redirects to the qualificacoes list" do
      qualificacao = Qualificacao.create! valid_attributes
      delete :destroy, {:id => qualificacao.to_param}, valid_session
      response.should redirect_to(qualificacoes_url)
    end
  end

end
